"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ScanText } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { BULLETIN_SERVICE_LABELS, BULLETIN_SERVICE_TYPES, type BulletinServiceType } from "@/lib/bulletin/scripture-parser";

type Bulletin = { id: string; title: string; sunday_date: string; pdf_url: string };
type Reading = { service_type: BulletinServiceType; raw_reference: string; normalized_label: string | null; source: string; confidence: number; status: string };
type Candidate = { serviceType: BulletinServiceType; rawReference: string; confidence: number };
async function call(path: string, init?: RequestInit) { const { data: { session } } = await supabase.auth.getSession(); return fetch(path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${session?.access_token || ""}`, ...init?.headers } }); }

export default function Page() {
  const router = useRouter(); const [bulletins, setBulletins] = useState<Bulletin[]>([]); const [selected, setSelected] = useState<Bulletin | null>(null); const [readings, setReadings] = useState<Reading[]>([]); const [manual, setManual] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const load = async (id?: string) => { const res = await call(`/api/admin/bulletin-scripture-readings${id ? `?bulletin_id=${id}` : ""}`); const json = await res.json(); if (id) setReadings(json.readings || []); else setBulletins(json.bulletins || []); };
  useEffect(() => { void (async () => { const { data } = await supabase.rpc("get_my_status"); if (!data?.[0] || !["admin", "office", "pastor"].includes(data[0].role)) { router.replace("/home"); return; } await load(); })(); }, [router]);
  const select = async (item: Bulletin) => { setSelected(item); setReadings([]); setNotice(""); await load(item.id); };
  const native = async () => { if (!selected) return; setBusy(true); const res = await call("/api/admin/bulletin-scripture-readings", { method: "POST", body: JSON.stringify({ action: "analyze_native", bulletin_id: selected.id }) }); const json = await res.json(); setNotice(res.ok ? `텍스트 분석 완료: ${json.saved}개 후보 저장${json.needs_ocr ? " · OCR fallback을 실행합니다." : ""}` : json.error); await load(selected.id); setBusy(false); if (res.ok && json.needs_ocr) await ocr(); };
  const ocr = async () => { if (!selected) return; setBusy(true); setNotice("1페이지 OCR 분석 중입니다…"); try {
    const { data: { session } } = await supabase.auth.getSession(); const file = await fetch(`/api/storage/bulletins/${selected.pdf_url}?stream=1`, { headers: { Authorization: `Bearer ${session?.access_token || ""}` } }); if (!file.ok) throw new Error("PDF를 불러오지 못했습니다.");
    const pdfjs = await import("pdfjs-dist"); pdfjs.GlobalWorkerOptions.workerSrc = "/pdf.worker.min.mjs"; const doc = await pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise; const page = await doc.getPage(1); const base = page.getViewport({ scale: 1 }); const viewport = page.getViewport({ scale: Math.min(2.25, 1800 / base.width) }); const canvas = document.createElement("canvas"); canvas.width = Math.floor(viewport.width); canvas.height = Math.floor(viewport.height); const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("OCR canvas 생성 실패"); await page.render({ canvas, canvasContext: ctx, viewport }).promise;
    const { createWorker } = await import("tesseract.js"); const worker = await createWorker(["kor", "eng"], 1); const result = await worker.recognize(canvas); await worker.terminate(); type Word = { text: string; bbox: { x0: number; y0: number; x1: number; y1: number } }; const words = (result.data as unknown as { words?: Word[] }).words || [];
    // Reconstruct visual lines from OCR bounding boxes, then relate a scripture anchor to its preceding service heading. No fixed pixel layout is used.
    const lines = words.reduce<Array<{ y: number; words: Word[] }>>((all, word) => { const existing = all.find((line) => Math.abs(line.y - word.bbox.y0) < 18); if (existing) existing.words.push(word); else all.push({ y: word.bbox.y0, words: [word] }); return all; }, []).sort((a, b) => a.y - b.y).map((line) => line.words.sort((a, b) => a.bbox.x0 - b.bbox.x0).map((word) => word.text).join(" "));
    const service = (text: string): BulletinServiceType | null => /주일.*(?:오전|1\s*부|2\s*부|3\s*부)/.test(text) ? "sunday_morning" : /(?:주일.*(?:오후|4\s*부)|4\s*부.*예배)/.test(text) ? "sunday_afternoon" : /수요.*(?:오전|1\s*부)/.test(text) ? "wednesday_morning" : /수요.*(?:오후|저녁|2\s*부)/.test(text) ? "wednesday_evening" : null;
    const candidates: Candidate[] = []; for (let i = 0; i < lines.length; i += 1) { if (!/성경\s*봉독/.test(lines[i])) continue; const heading = [...lines.slice(0, i)].reverse().find(service); const serviceType = heading ? service(heading) : null; const raw = `${lines[i]} ${lines[i + 1] || ""}`.match(/([가-힣0-9]+\s*\d{1,3}\s*(?::|장\s*)\s*\d{1,3}\s*(?:절)?\s*(?:[-~∼]\s*\d{1,3}\s*(?:절)?)?)/)?.[1]; if (serviceType && raw) candidates.push({ serviceType, rawReference: raw.replace(/장\s*/g, ":").replace(/절/g, "").replace(/[~∼]/g, "-").replace(/\s+/g, " ").trim(), confidence: .68 }); }
    const saved = await call("/api/admin/bulletin-scripture-readings", { method: "POST", body: JSON.stringify({ action: "save_ocr_candidates", bulletin_id: selected.id, candidates }) }); const json = await saved.json(); setNotice(saved.ok ? `OCR 분석 완료: ${json.saved}개 후보 저장` : json.error); await load(selected.id);
  } catch (error) { setNotice(error instanceof Error ? error.message : "OCR 분석 실패"); } finally { setBusy(false); } };
  const verify = async (type: BulletinServiceType) => { if (!selected || !manual[type]?.trim()) return; setBusy(true); const res = await call("/api/admin/bulletin-scripture-readings", { method: "POST", body: JSON.stringify({ action: "save_reading", bulletin_id: selected.id, reading: { serviceType: type, rawReference: manual[type], status: "verified" } }) }); const json = await res.json(); setNotice(res.ok && json.ok ? "검증 및 저장했습니다." : json.error || "저장 실패"); await load(selected.id); setBusy(false); };
  return <main style={page}><header style={head}><button onClick={() => router.push("/home")} style={back}><ArrowLeft size={18}/></button><div><h1 style={{ margin: 0, fontSize: 21 }}>주보 성경봉독 관리</h1><small>후보는 확인 전까지 성도에게 보이지 않습니다.</small></div></header><div style={grid}><section style={card}><b>최근 주보</b>{bulletins.map((item) => <button key={item.id} onClick={() => void select(item)} style={{ ...itemButton, ...(selected?.id === item.id ? { background: "var(--accent-soft)" } : {}) }}>{item.sunday_date}<br/><small>{item.title}</small></button>)}</section><section style={card}>{selected ? <><b>{selected.sunday_date} 주보</b><p><button disabled={busy} onClick={() => void native()} style={primary}><ScanText size={16}/>텍스트 분석</button> <button disabled={busy} onClick={() => void ocr()} style={secondary}>1페이지 OCR 분석</button></p>{notice && <p style={{ fontSize: 13 }}>{notice}</p>}{readings.map((reading) => <div key={reading.service_type} style={readingStyle}><b>{BULLETIN_SERVICE_LABELS[reading.service_type]}</b><div>{reading.normalized_label || reading.raw_reference}</div><small>{reading.status} · {reading.source} · confidence {reading.confidence}</small></div>)}<h2 style={{ fontSize: 15 }}>직접 입력 및 확인</h2>{BULLETIN_SERVICE_TYPES.map((type) => <div key={type} style={{ display: "flex", gap: 7, margin: "8px 0", flexWrap: "wrap" }}><label style={{ minWidth: 105, fontWeight: 700 }}>{BULLETIN_SERVICE_LABELS[type]}</label><input value={manual[type] || ""} onChange={(e) => setManual({ ...manual, [type]: e.target.value })} placeholder="예: 출애굽기 23:10-13" style={input}/><button disabled={busy} onClick={() => void verify(type)} style={secondary}>검증 후 저장</button></div>)}</> : <p>왼쪽에서 주보를 선택하세요.</p>}</section></div></main>;
}
const page: React.CSSProperties = { maxWidth: 1080, margin: "0 auto", padding: 20, color: "var(--ink)" }; const head: React.CSSProperties = { display: "flex", alignItems: "center", gap: 12, marginBottom: 18 }; const back: React.CSSProperties = { border: "1px solid var(--hairline)", background: "var(--surface)", borderRadius: 8, width: 36, height: 36, display: "grid", placeItems: "center", cursor: "pointer" }; const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "minmax(220px,.8fr) minmax(0,2fr)", gap: 16 }; const card: React.CSSProperties = { background: "var(--surface)", border: "1px solid var(--hairline)", borderRadius: 12, padding: 15 }; const itemButton: React.CSSProperties = { width: "100%", textAlign: "left", background: "transparent", border: 0, borderBottom: "1px solid var(--hairline)", padding: "12px 4px", cursor: "pointer", color: "var(--ink)", fontFamily: "inherit" }; const primary: React.CSSProperties = { border: 0, borderRadius: 8, background: "var(--accent)", color: "#fff", padding: "9px 12px", fontWeight: 800, cursor: "pointer", display: "inline-flex", gap: 6, alignItems: "center" }; const secondary: React.CSSProperties = { border: "1px solid var(--hairline)", borderRadius: 7, background: "var(--surface)", padding: "7px 9px", cursor: "pointer", fontWeight: 700 }; const input: React.CSSProperties = { flex: 1, minWidth: 180, border: "1px solid var(--hairline)", borderRadius: 7, padding: "7px 9px", fontFamily: "inherit" }; const readingStyle: React.CSSProperties = { borderTop: "1px solid var(--hairline)", padding: "10px 0" };
