"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Search, Users, X } from "lucide-react";
import { useConfirm } from "@/components/ConfirmDialog";
import ModalBackdrop from "@/components/ModalBackdrop";
import Avatar from "@/components/messenger/MessengerAvatar";
import { EmptyState, LoadingView } from "@/components/StatusViews";
import { messengerErrorMessage, messengerRoleLabel, toggleMessengerUser } from "@/lib/messenger-utils";
import { searchMessengerUsers, type MessengerConversation, type MessengerParticipant, type MessengerUser } from "@/lib/messenger";

export default function GroupManagementModal({ conversation, participants, myUserId, onClose, onRename, onAddMembers, onRemoveMember, onError }: { conversation: MessengerConversation; participants: MessengerParticipant[]; myUserId: string | null; onClose: () => void; onRename: (title: string) => Promise<void>; onAddMembers: (ids: string[]) => Promise<void>; onRemoveMember: (id: string) => Promise<void>; onError: (message: string) => void }) {
  const { confirm } = useConfirm(); const [title, setTitle] = useState(conversation.title || conversation.display_title); const [query, setQuery] = useState(""); const [users, setUsers] = useState<MessengerUser[]>([]); const [selected, setSelected] = useState<MessengerUser[]>([]); const [loading, setLoading] = useState(false); const [savingTitle, setSavingTitle] = useState(false); const [adding, setAdding] = useState(false); const [removingId, setRemovingId] = useState<string | null>(null);
  const participantIds = useMemo(() => new Set(participants.map((item) => item.user_id)), [participants]); const filteredUsers = users.filter((user) => !participantIds.has(user.user_id));
  useEffect(() => { let cancelled = false; const timer = window.setTimeout(async () => { setLoading(true); try { const rows = await searchMessengerUsers(query, 30); if (!cancelled) setUsers(rows); } catch (error) { if (!cancelled) onError(messengerErrorMessage(error)); } finally { if (!cancelled) setLoading(false); } }, 180); return () => { cancelled = true; window.clearTimeout(timer); }; }, [onError, query]);
  const saveTitle = async () => { const next = title.trim(); if (!next || savingTitle) return; setSavingTitle(true); try { await onRename(next); } finally { setSavingTitle(false); } };
  const addSelected = async () => { if (!selected.length || adding) return; setAdding(true); try { await onAddMembers(selected.map((user) => user.user_id)); setSelected([]); setQuery(""); } finally { setAdding(false); } };
  const removeMember = async (participant: MessengerParticipant) => { if (participant.user_id === myUserId || removingId || !await confirm(`${participant.name || "이 멤버"}님을 대화방에서 내보낼까요?`)) return; setRemovingId(participant.user_id); try { await onRemoveMember(participant.user_id); } finally { setRemovingId(null); } };
  return <ModalBackdrop onClose={onClose} style={overlay}><div onClick={(event) => event.stopPropagation()} style={modal}><div style={header}><strong style={heading}><Users size={18} /> 그룹 관리</strong><button onClick={onClose} style={icon}><X size={17} /></button></div><div style={titleRow}><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={80} style={input} /><button onClick={saveTitle} disabled={!title.trim() || savingTitle} style={primary}>저장</button></div><Label>참여자 {participants.length}명</Label><div style={{ ...list, maxHeight: 260 }}>{participants.map((person) => <div key={person.user_id} style={row}><Avatar title={person.name || "U"} src={person.avatar_url} /><div style={{ flex: 1 }}><b>{person.name || "이름 없음"}{person.user_id === myUserId ? " (나)" : ""}</b><small>{person.role === "owner" ? "방장" : person.sub_role || "참여자"}</small></div>{person.user_id !== myUserId && <button onClick={() => removeMember(person)} disabled={removingId === person.user_id} style={secondary}>내보내기</button>}</div>)}</div><Label>참여자 추가</Label><div style={search}><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름 또는 직분 검색" style={searchInput} /></div>{selected.length > 0 && <div style={chips}>{selected.map((person) => <span key={person.user_id} style={chip}>{person.name || "이름 없음"}<button onClick={() => setSelected((current) => current.filter((item) => item.user_id !== person.user_id))} style={remove}><X size={12} /></button></span>)}</div>}<div style={list}>{loading ? <LoadingView padding={28} /> : filteredUsers.length === 0 ? <EmptyState message="추가할 사용자가 없습니다." padding={34} /> : filteredUsers.map((person) => <button key={person.user_id} onClick={() => setSelected((current) => toggleMessengerUser(current, person))} style={row}><Avatar title={person.name || "U"} src={person.avatar_url} /><div style={{ flex: 1 }}><b>{person.name || "이름 없음"}</b><small>{person.sub_role || messengerRoleLabel(person.role)}</small></div>{selected.some((item) => item.user_id === person.user_id) && <Check size={17} color="var(--accent)" />}</button>)}</div><div style={footer}><button onClick={onClose} style={secondary}>닫기</button><button onClick={addSelected} disabled={!selected.length || adding} style={primary}>추가</button></div></div></ModalBackdrop>;
}
function Label({ children }: { children: React.ReactNode }) { return <div style={{ margin: "8px 4px 6px", fontSize: 11, fontWeight: 900, color: "var(--ink-faint)" }}>{children}</div>; }
const overlay = { position: "fixed", inset: 0, zIndex: 200, background: "rgba(43,39,34,0.48)", display: "flex", alignItems: "center", justifyContent: "center", padding: 12 } as const; const modal = { width: "min(560px, calc(100vw - 24px))", maxHeight: "calc(100dvh - 24px)", overflowY: "auto", background: "var(--card)", borderRadius: 10, border: "1px solid var(--hairline)", padding: 16 } as const; const header = { display: "flex", justifyContent: "space-between", marginBottom: 14 } as const; const heading = { display: "flex", alignItems: "center", gap: 8, fontSize: 17 } as const; const icon = { width: 34, height: 34, border: "1px solid var(--hairline)", borderRadius: 8, background: "var(--card)", color: "var(--ink)" } as const; const titleRow = { display: "grid", gridTemplateColumns: "1fr auto", gap: 8, marginBottom: 14 } as const; const input = { height: 40, border: "1px solid var(--hairline)", borderRadius: 8, padding: "0 12px", background: "var(--surface)", color: "var(--ink)" } as const; const primary = { height: 38, padding: "0 16px", border: "none", borderRadius: 8, background: "var(--accent)", color: "#fff", fontWeight: 900 } as const; const secondary = { ...primary, border: "1px solid var(--hairline)", background: "var(--surface)", color: "var(--ink-mid)" } as const; const list = { maxHeight: 340, overflowY: "auto", border: "1px solid var(--hairline)", borderRadius: 8 } as const; const row = { width: "100%", minHeight: 62, border: "none", borderBottom: "1px solid var(--hairline)", background: "transparent", display: "flex", alignItems: "center", gap: 10, padding: "9px 10px", textAlign: "left", color: "var(--ink)" } as const; const search = { height: 42, border: "1px solid var(--hairline)", borderRadius: 8, display: "flex", alignItems: "center", gap: 8, padding: "0 12px", marginBottom: 10 } as const; const searchInput = { flex: 1, border: "none", outline: "none", background: "transparent", color: "var(--ink)" } as const; const chips = { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 10 } as const; const chip = { height: 26, padding: "0 6px 0 9px", borderRadius: 999, background: "var(--accent-soft)", color: "var(--accent)", display: "inline-flex", alignItems: "center", gap: 4, fontSize: 12, fontWeight: 900 } as const; const remove = { border: "none", background: "transparent", color: "inherit" } as const; const footer = { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 14 } as const;
